Fix building on gcc.
For some mysterious reason gcc complains in the `MethodsFor` definition meant
for the non-inline case, if the inline case is excluded using SFINAE with
the condition using `IsInline` defined as an alias to
`std::integral_constant<bool, _>`:

```
./riegeli/base/any_dependency.h: In instantiation of 'struct riegeli::any_dependency_internal::MethodsFor<riegeli::Reader*, 200, 8, riegeli::LimitingReader<>, void>':
[...]
./riegeli/base/any_dependency.h:544:15: error: no type named 'type' in 'struct std::enable_if<false, void>'
  544 |   static void Construct(Storage self, const Manager& manager) {
      |               ^~~~~~~~~
```

But it is fine if `IsInline` is defined by inheriting from `std::false_type` by
default, with a conditional specialization inheriting from `std::true_type`.

PiperOrigin-RevId: 429002660